import type { ReviewerRole } from "./review";

export const REVIEW_BASIS_IDS = [
  "WCAG22-1.4.1",
  "WCAG22-1.4.3",
  "WCAG22-2.5.8",
  "WCAG22-3.2.4",
  "WCAG22-3.3.2",
  "APPLE-DESIGN-TIPS",
  "APPLE-HIT-TARGET-44",
  "NNG-VISIBILITY-OF-STATUS",
  "NNG-ERROR-PREVENTION",
] as const;

export type ReviewBasisId = (typeof REVIEW_BASIS_IDS)[number];
export type ReviewBasisKind = "standard" | "guideline" | "heuristic";

export type ReviewBasis = {
  id: ReviewBasisId;
  title: string;
  publisher: string;
  kind: ReviewBasisKind;
  url: string;
  summary: string;
  roles: readonly ReviewerRole[];
};

/**
 * This is deliberately a small, reviewed catalogue.  It is not generated by
 * the model: every source and claim below was checked against its publisher.
 */
export const REVIEW_BASIS_LIBRARY: readonly ReviewBasis[] = [
  {
    id: "WCAG22-1.4.1",
    title: "WCAG 2.2 SC 1.4.1 - Use of Color",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/use-of-color",
    summary: "Information, actions, and status must not be conveyed by colour alone.",
    roles: ["accessibility"],
  },
  {
    id: "WCAG22-1.4.3",
    title: "WCAG 2.2 SC 1.4.3 - Contrast (Minimum)",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum",
    summary: "Normal text needs a 4.5:1 contrast ratio at Level AA, subject to the criterion's exceptions.",
    roles: ["accessibility"],
  },
  {
    id: "WCAG22-2.5.8",
    title: "WCAG 2.2 SC 2.5.8 - Target Size (Minimum)",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum",
    summary: "The WCAG 2.2 AA minimum pointer target is 24 by 24 CSS pixels, with defined exceptions.",
    roles: ["accessibility", "interaction"],
  },
  {
    id: "WCAG22-3.2.4",
    title: "WCAG 2.2 SC 3.2.4 - Consistent Identification",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/consistent-identification",
    summary: "Repeated components with the same functionality should be identified consistently across a set of pages.",
    roles: ["accessibility", "interaction"],
  },
  {
    id: "WCAG22-3.3.2",
    title: "WCAG 2.2 SC 3.3.2 - Labels or Instructions",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions",
    summary: "Inputs that require user action need labels or instructions.",
    roles: ["accessibility", "interaction"],
  },
  {
    id: "APPLE-DESIGN-TIPS",
    title: "Apple UI Design Tips - Alignment, Spacing, Organization",
    publisher: "Apple Developer",
    kind: "guideline",
    url: "https://developer.apple.com/design/tips/",
    summary: "Professional platform guidance on readable organization, alignment, spacing, contrast, and text legibility; it is a recommendation, not a universal conformance standard.",
    roles: ["visual", "accessibility", "interaction"],
  },
  {
    id: "APPLE-HIT-TARGET-44",
    title: "Apple UI Design Tips - 44 by 44 pt Hit Targets",
    publisher: "Apple Developer",
    kind: "guideline",
    url: "https://developer.apple.com/design/tips/",
    summary: "Apple recommends touch controls measure at least 44 by 44 points. This is a mobile-platform recommendation, not the WCAG AA minimum.",
    roles: ["accessibility", "interaction"],
  },
  {
    id: "NNG-VISIBILITY-OF-STATUS",
    title: "Nielsen Norman Group - Visibility of System Status",
    publisher: "Nielsen Norman Group",
    kind: "heuristic",
    url: "https://www.nngroup.com/articles/ten-usability-heuristics/",
    summary: "A professional usability heuristic: systems should keep users informed about what is happening through timely feedback. It is not a formal compliance rule.",
    roles: ["interaction"],
  },
  {
    id: "NNG-ERROR-PREVENTION",
    title: "Nielsen Norman Group - Error Prevention",
    publisher: "Nielsen Norman Group",
    kind: "heuristic",
    url: "https://www.nngroup.com/articles/ten-usability-heuristics/",
    summary: "A professional usability heuristic: prevent likely errors before they happen. It is not a formal compliance rule.",
    roles: ["interaction"],
  },
] as const;

const basisById = new Map(REVIEW_BASIS_LIBRARY.map((basis) => [basis.id, basis]));

export function getReviewBasis(id: ReviewBasisId): ReviewBasis {
  const basis = basisById.get(id);
  if (!basis) throw new Error(`Unknown review basis: ${id}`);
  return basis;
}

export function getReviewBasesForRole(role: ReviewerRole): readonly ReviewBasis[] {
  return REVIEW_BASIS_LIBRARY.filter((basis) => basis.roles.includes(role));
}
