import type { ReviewerRole } from "./review";

export const REVIEW_BASIS_IDS = [
  "WCAG22-1.3.1",
  "WCAG22-1.3.2",
  "WCAG22-1.4.1",
  "WCAG22-1.4.3",
  "WCAG22-2.4.4",
  "WCAG22-2.4.6",
  "WCAG22-2.5.8",
  "WCAG22-3.2.2",
  "WCAG22-3.2.4",
  "WCAG22-3.3.1",
  "WCAG22-3.3.2",
  "WCAG22-3.3.4",
  "W3C-COGA-CLEAR-CONTENT",
  "W3C-COGA-CONTENT-USABLE",
  "APPLE-DESIGN-TIPS",
  "APPLE-DESIGN-PRINCIPLES",
  "APPLE-ACCESSIBILITY",
  "APPLE-FEEDBACK",
  "APPLE-HIT-TARGET-44",
  "MICROSOFT-INCLUSIVE-DESIGN",
  "NNG-VISUAL-DESIGN",
  "NNG-VISIBILITY-OF-STATUS",
  "NNG-ERROR-PREVENTION",
] as const;

export type ReviewBasisId = (typeof REVIEW_BASIS_IDS)[number];
export type ReviewBasisKind = "standard" | "guideline" | "heuristic";

export type ReviewBasis = {
  id: ReviewBasisId;
  title: string;
  publisher: string;
  kind: ReviewBasisKind;
  url: string;
  summary: string;
  roles: readonly ReviewerRole[];
};

/**
 * This is deliberately a small, reviewed catalogue.  It is not generated by
 * the model: every source and claim below was checked against its publisher.
 */
export const REVIEW_BASIS_LIBRARY: readonly ReviewBasis[] = [
  {
    id: "WCAG22-1.3.1",
    title: "WCAG 2.2 SC 1.3.1 - Info and Relationships",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships",
    summary: "Information, structure, and relationships conveyed through presentation must also be programmatically determinable or available in text; static designs can only evidence the visible relationship.",
    roles: ["visual", "accessibility"],
  },
  {
    id: "WCAG22-1.3.2",
    title: "WCAG 2.2 SC 1.3.2 - Meaningful Sequence",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/meaningful-sequence",
    summary: "When presentation order affects meaning, a correct reading sequence must be programmatically determinable; implementation order cannot be confirmed from a static design alone.",
    roles: ["accessibility"],
  },
  {
    id: "WCAG22-1.4.1",
    title: "WCAG 2.2 SC 1.4.1 - Use of Color",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/use-of-color",
    summary: "Information, actions, and status must not be conveyed by colour alone.",
    roles: ["accessibility"],
  },
  {
    id: "WCAG22-1.4.3",
    title: "WCAG 2.2 SC 1.4.3 - Contrast (Minimum)",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum",
    summary: "Normal text needs a 4.5:1 contrast ratio at Level AA, subject to the criterion's exceptions.",
    roles: ["accessibility"],
  },
  {
    id: "WCAG22-2.4.4",
    title: "WCAG 2.2 SC 2.4.4 - Link Purpose (In Context)",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-in-context",
    summary: "A link's purpose should be determinable from its text or from its text together with programmatically associated context, subject to the criterion's exception.",
    roles: ["interaction"],
  },
  {
    id: "WCAG22-2.4.6",
    title: "WCAG 2.2 SC 2.4.6 - Headings and Labels",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/headings-and-labels",
    summary: "Headings and labels should describe the topic or purpose of the content or control they identify.",
    roles: ["accessibility", "interaction"],
  },
  {
    id: "WCAG22-2.5.8",
    title: "WCAG 2.2 SC 2.5.8 - Target Size (Minimum)",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum",
    summary: "The WCAG 2.2 AA minimum pointer target is 24 by 24 CSS pixels, with defined exceptions.",
    roles: ["accessibility", "interaction"],
  },
  {
    id: "WCAG22-3.2.2",
    title: "WCAG 2.2 SC 3.2.2 - On Input",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/on-input",
    summary: "Changing the setting of a user interface component must not automatically cause an unexpected change of context unless users were advised beforehand.",
    roles: ["accessibility", "interaction"],
  },
  {
    id: "WCAG22-3.2.4",
    title: "WCAG 2.2 SC 3.2.4 - Consistent Identification",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/consistent-identification",
    summary: "Repeated components with the same functionality should be identified consistently across a set of pages.",
    roles: ["accessibility", "interaction"],
  },
  {
    id: "WCAG22-3.3.1",
    title: "WCAG 2.2 SC 3.3.1 - Error Identification",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/error-identification",
    summary: "When an input error is automatically detected, the item in error must be identified and the error described in text.",
    roles: ["accessibility", "interaction"],
  },
  {
    id: "WCAG22-3.3.2",
    title: "WCAG 2.2 SC 3.3.2 - Labels or Instructions",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions",
    summary: "Inputs that require user action need labels or instructions.",
    roles: ["accessibility", "interaction"],
  },
  {
    id: "WCAG22-3.3.4",
    title: "WCAG 2.2 SC 3.3.4 - Error Prevention (Legal, Financial, Data)",
    publisher: "W3C",
    kind: "standard",
    url: "https://www.w3.org/WAI/WCAG22/Understanding/error-prevention-legal-financial-data",
    summary: "For specified legal, financial, data-modifying, and test-response submissions, users need a reversal, validation, or review-and-confirm mechanism.",
    roles: ["interaction"],
  },
  {
    id: "W3C-COGA-CLEAR-CONTENT",
    title: "W3C COGA - Use Clear and Understandable Content",
    publisher: "W3C WAI",
    kind: "guideline",
    url: "https://www.w3.org/WAI/WCAG2/supplemental/objectives/o3-clear-content/",
    summary: "Supplemental cognitive-accessibility guidance recommends familiar words, concise and unambiguous language, short text blocks, and clear visual organization. It is not required for WCAG conformance.",
    roles: ["accessibility"],
  },
  {
    id: "W3C-COGA-CONTENT-USABLE",
    title: "W3C COGA - Making Content Usable for People with Cognitive and Learning Disabilities",
    publisher: "W3C",
    kind: "guideline",
    url: "https://www.w3.org/TR/coga-usable/",
    summary: "A W3C Working Group Note on reducing cognitive barriers in language, structure, memory, attention, and task completion. It supplements WCAG and is not a conformance standard.",
    roles: ["accessibility"],
  },
  {
    id: "APPLE-DESIGN-TIPS",
    title: "Apple UI Design Tips - Alignment, Spacing, Organization",
    publisher: "Apple Developer",
    kind: "guideline",
    url: "https://developer.apple.com/design/tips/",
    summary: "Professional platform guidance on readable organization, alignment, spacing, contrast, and text legibility; it is a recommendation, not a universal conformance standard.",
    roles: ["visual", "accessibility", "interaction"],
  },
  {
    id: "APPLE-DESIGN-PRINCIPLES",
    title: "Apple Human Interface Guidelines - Design Principles",
    publisher: "Apple Developer",
    kind: "guideline",
    url: "https://developer.apple.com/design/human-interface-guidelines/design-principles",
    summary: "Platform guidance supporting clear hierarchy, consistent presentation and interaction, and interfaces that make the primary task understandable.",
    roles: ["visual", "interaction"],
  },
  {
    id: "APPLE-ACCESSIBILITY",
    title: "Apple Human Interface Guidelines - Accessibility",
    publisher: "Apple Developer",
    kind: "guideline",
    url: "https://developer.apple.com/design/human-interface-guidelines/accessibility/",
    summary: "Inclusive interface guidance for low vision, color blindness, adaptable presentation, and situations where lighting or screen brightness affects use.",
    roles: ["accessibility"],
  },
  {
    id: "APPLE-FEEDBACK",
    title: "Apple Human Interface Guidelines - Feedback",
    publisher: "Apple Developer",
    kind: "guideline",
    url: "https://developer.apple.com/design/human-interface-guidelines/feedback",
    summary: "Interfaces should provide clear, timely feedback that helps people understand an action's state, result, and any needed next step.",
    roles: ["interaction"],
  },
  {
    id: "APPLE-HIT-TARGET-44",
    title: "Apple UI Design Tips - 44 by 44 pt Hit Targets",
    publisher: "Apple Developer",
    kind: "guideline",
    url: "https://developer.apple.com/design/tips/",
    summary: "Apple recommends touch controls measure at least 44 by 44 points. This is a mobile-platform recommendation, not the WCAG AA minimum.",
    roles: ["accessibility", "interaction"],
  },
  {
    id: "MICROSOFT-INCLUSIVE-DESIGN",
    title: "Microsoft Inclusive Design - Inclusive 101",
    publisher: "Microsoft Design",
    kind: "guideline",
    url: "https://inclusive.microsoft.design/articles/inclusive-101-guidebook",
    summary: "Inclusive-design guidance asks teams to recognize exclusion across permanent, temporary, and situational limitations and learn from diverse user needs.",
    roles: ["accessibility"],
  },
  {
    id: "NNG-VISUAL-DESIGN",
    title: "Nielsen Norman Group - Principles of Visual Design",
    publisher: "Nielsen Norman Group",
    kind: "heuristic",
    url: "https://www.nngroup.com/articles/principles-visual-design/",
    summary: "Professional visual-design guidance on hierarchy, balance, contrast, and consistent organization. It is not a formal conformance rule.",
    roles: ["visual"],
  },
  {
    id: "NNG-VISIBILITY-OF-STATUS",
    title: "Nielsen Norman Group - Visibility of System Status",
    publisher: "Nielsen Norman Group",
    kind: "heuristic",
    url: "https://www.nngroup.com/articles/ten-usability-heuristics/",
    summary: "A professional usability heuristic: systems should keep users informed about what is happening through timely feedback. It is not a formal compliance rule.",
    roles: ["interaction"],
  },
  {
    id: "NNG-ERROR-PREVENTION",
    title: "Nielsen Norman Group - Error Prevention",
    publisher: "Nielsen Norman Group",
    kind: "heuristic",
    url: "https://www.nngroup.com/articles/ten-usability-heuristics/",
    summary: "A professional usability heuristic: prevent likely errors before they happen. It is not a formal compliance rule.",
    roles: ["interaction"],
  },
] as const;

const basisById = new Map(REVIEW_BASIS_LIBRARY.map((basis) => [basis.id, basis]));

export function getReviewBasis(id: ReviewBasisId): ReviewBasis {
  const basis = basisById.get(id);
  if (!basis) throw new Error(`Unknown review basis: ${id}`);
  return basis;
}

export function getReviewBasesForRole(role: ReviewerRole): readonly ReviewBasis[] {
  return REVIEW_BASIS_LIBRARY.filter((basis) => basis.roles.includes(role));
}
